enum ActionTypes {
  GET_PROFILE_DETAILS = 'ADMIN_UI/PROFILE_MANAGEMENT/GET_PROFILE_DETAILS',
  GET_PROFILE_DETAILS_SUCCESS = 'ADMIN_UI/PROFILE_MANAGEMENT/GET_PROFILE_DETAILS_SUCCESS',
  GET_PROFILE_DETAILS_FAILED = 'ADMIN_UI/PROFILE_MANAGEMENT/GET_PROFILE_DETAILS_FAILED',

  UPDATE_PROFILE = 'ADMIN_UI/PROFILE_MANAGEMENT/UPDATE_PROFILE',
  UPDATE_PROFILE_SUCCESS = 'ADMIN_UI/PROFILE_MANAGEMENT/UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILED = 'ADMIN_UI/PROFILE_MANAGEMENT/UPDATE_PROFILE_FAILED',

  UPDATE_PROFILE_IMAGE = 'ADMIN_UI/PROFILE_MANAGEMENT/UPDATE_PROFILE_IMAGE',
  UPDATE_PROFILE_IMAGE_SUCCESS = 'ADMIN_UI/PROFILE_MANAGEMENT/UPDATE_PROFILE_IMAGE_SUCCESS',
  UPDATE_PROFILE_IMAGE_FAILED = 'ADMIN_UI/PROFILE_MANAGEMENT/UPDATE_PROFILE_IMAGE_FAILED',

  UPDATE_PASSWORD = 'ADMIN_UI/PROFILE_MANAGEMENT/UPDATE_PASSWORD',
  UPDATE_PASSWORD_SUCCESS = 'ADMIN_UI/PROFILE_MANAGEMENT/UPDATE_PASSWORD_SUCCESS',
  UPDATE_PASSWORD_FAILED = 'ADMIN_UI/PROFILE_MANAGEMENT/UPDATE_PASSWORD_FAILED',

  RESET_REDUX = 'ADMIN_UI/PROFILE_MANAGEMENT/RESET_REDUX'
}

export default ActionTypes;
