enum ActionTypes {
  GET_RESTAURANT_LIST = 'ADMIN_UI/RESTAURANT_MANAGEMENT/GET_RESTAURANT_LIST',
  GET_RESTAURANT_LIST_SUCCESS = 'ADMIN_UI/RESTAURANT_MANAGEMENT/GET_RESTAURANT_LIST_SUCCESS',
  GET_RESTAURANT_LIST_FAILED = 'ADMIN_UI/RESTAURANT_MANAGEMENT/GET_RESTAURANT_LIST_FAILED',

  ADD_RESTAURANT = 'ADMIN_UI/RESTAURANT_MANAGEMENT/ADD_RESTAURANT',
  ADD_RESTAURANT_SUCCESS = 'ADMIN_UI/RESTAURANT_MANAGEMENT/ADD_RESTAURANT_SUCCESS',
  ADD_RESTAURANT_FAILED = 'ADMIN_UI/RESTAURANT_MANAGEMENT/ADD_RESTAURANT_FAILED',

  UPDATE_RESTAURANT = 'ADMIN_UI/RESTAURANT_MANAGEMENT/UPDATE_RESTAURANT',
  UPDATE_RESTAURANT_SUCCESS = 'ADMIN_UI/RESTAURANT_MANAGEMENT/UPDATE_RESTAURANT_SUCCESS',
  UPDATE_RESTAURANT_FAILED = 'ADMIN_UI/RESTAURANT_MANAGEMENT/UPDATE_RESTAURANT_FAILED',

  DELETE_RESTAURANT = 'ADMIN_UI/RESTAURANT_MANAGEMENT/DELETE_RESTAURANT',
  DELETE_RESTAURANT_SUCCESS = 'ADMIN_UI/RESTAURANT_MANAGEMENT/DELETE_RESTAURANT_SUCCESS',
  DELETE_RESTAURANT_FAILED = 'ADMIN_UI/RESTAURANT_MANAGEMENT/DELETE_RESTAURANT_FAILED',

  GET_RESTAURANT = 'ADMIN_UI/RESTAURANT_MANAGEMENT/GET_RESTAURANT',
  GET_RESTAURANT_SUCCESS = 'ADMIN_UI/RESTAURANT_MANAGEMENT/GET_RESTAURANT_SUCCESS',
  GET_RESTAURANT_FAILED = 'ADMIN_UI/RESTAURANT_MANAGEMENT/GET_RESTAURANT_FAILED',

  GET_ALL_LOCATIONS = 'ADMIN_UI/RESTAURANT_MANAGEMENT/GET_ALL_LOCATIONS',
  GET_ALL_LOCATIONS_SUCCESS = 'ADMIN_UI/RESTAURANT_MANAGEMENT/GET_ALL_LOCATIONS_SUCCESS',
  GET_ALL_LOCATIONS_FAILED = 'ADMIN_UI/RESTAURANT_MANAGEMENT/GET_ALL_LOCATIONS_FAILED',

  RESET_REDUX = 'ADMIN_UI/RESTAURANT_MANAGEMENT/RESET_REDUX'
}

export default ActionTypes;
