enum ActionTypes {
  GET_DASHBOARD_DATA = 'ADMIN_UI/DASHBOARD_MANAGEMENT/GET_DASHBOARD_DATA',
  GET_DASHBOARD_DATA_SUCCESS = 'ADMIN_UI/DASHBOARD_MANAGEMENT/GET_DASHBOARD_DATA_SUCCESS',
  GET_DASHBOARD_DATA_FAILED = 'ADMIN_UI/DASHBOARD_MANAGEMENT/GET_DASHBOARD_DATA_FAILED',

  RESET_REDUX = 'ADMIN_UI/DASHBOARD_MANAGEMENT/RESET_REDUX'
}

export default ActionTypes;
