enum ActionTypes {
  GET_LOCATION_LIST = 'ADMIN_UI/LOCATION_MANAGEMENT/GET_LOCATION_LIST',
  GET_LOCATION_LIST_SUCCESS = 'ADMIN_UI/LOCATION_MANAGEMENT/GET_LOCATION_LIST_SUCCESS',
  GET_LOCATION_LIST_FAILED = 'ADMIN_UI/LOCATION_MANAGEMENT/GET_LOCATION_LIST_FAILED',

  ADD_LOCATION = 'ADMIN_UI/LOCATION_MANAGEMENT/ADD_LOCATION',
  ADD_LOCATION_SUCCESS = 'ADMIN_UI/LOCATION_MANAGEMENT/ADD_LOCATION_SUCCESS',
  ADD_LOCATION_FAILED = 'ADMIN_UI/LOCATION_MANAGEMENT/ADD_LOCATION_FAILED',

  UPDATE_LOCATION = 'ADMIN_UI/LOCATION_MANAGEMENT/UPDATE_LOCATION',
  UPDATE_LOCATION_SUCCESS = 'ADMIN_UI/LOCATION_MANAGEMENT/UPDATE_LOCATION_SUCCESS',
  UPDATE_LOCATION_FAILED = 'ADMIN_UI/LOCATION_MANAGEMENT/UPDATE_LOCATION_FAILED',

  DELETE_LOCATION = 'ADMIN_UI/LOCATION_MANAGEMENT/DELETE_LOCATION',
  DELETE_LOCATION_SUCCESS = 'ADMIN_UI/LOCATION_MANAGEMENT/DELETE_LOCATION_SUCCESS',
  DELETE_LOCATION_FAILED = 'ADMIN_UI/LOCATION_MANAGEMENT/DELETE_LOCATION_FAILED',

  GET_LOCATION = 'ADMIN_UI/LOCATION_MANAGEMENT/GET_LOCATION',
  GET_LOCATION_SUCCESS = 'ADMIN_UI/LOCATION_MANAGEMENT/GET_LOCATION_SUCCESS',
  GET_LOCATION_FAILED = 'ADMIN_UI/LOCATION_MANAGEMENT/GET_LOCATION_FAILED',

  RESET_REDUX = 'ADMIN_UI/LOCATION_MANAGEMENT/RESET_REDUX'
}

export default ActionTypes;
