enum ActionTypes {
  GET_USER_LIST = 'ADMIN_UI/USER_MANAGEMENT/GET_USER_LIST',
  GET_USER_LIST_SUCCESS = 'ADMIN_UI/USER_MANAGEMENT/GET_USER_LIST_SUCCESS',
  GET_USER_LIST_FAILED = 'ADMIN_UI/USER_MANAGEMENT/GET_USER_LIST_FAILED',

  GET_USER = 'ADMIN_UI/USER_MANAGEMENT/GET_USER',
  GET_USER_SUCCESS = 'ADMIN_UI/USER_MANAGEMENT/GET_USER_SUCCESS',
  GET_USER_FAILED = 'ADMIN_UI/USER_MANAGEMENT/GET_USER_FAILED',

  GET_ACTIVITY_BY_USER = 'ADMIN_UI/USER_MANAGEMENT/GET_ACTIVITY_BY_USER',
  GET_ACTIVITY_BY_USER_SUCCESS = 'ADMIN_UI/USER_MANAGEMENT/GET_ACTIVITY_BY_USER_SUCCESS',
  GET_ACTIVITY_BY_USER_FAILED = 'ADMIN_UI/USER_MANAGEMENT/GET_ACTIVITY_BY_USER_FAILED',

  RESET_REDUX = 'ADMIN_UI/USER_MANAGEMENT/RESET_REDUX'
}

export default ActionTypes;
