enum ActionTypes {
  GET_ACTIVITY_LIST = 'ADMIN_UI/ACTIVITY_MANAGEMENT/GET_ACTIVITY_LIST',
  GET_ACTIVITY_LIST_SUCCESS = 'ADMIN_UI/ACTIVITY_MANAGEMENT/GET_ACTIVITY_LIST_SUCCESS',
  GET_ACTIVITY_LIST_FAILED = 'ADMIN_UI/ACTIVITY_MANAGEMENT/GET_ACTIVITY_LIST_FAILED',

  ADD_ACTIVITY = 'ADMIN_UI/ACTIVITY_MANAGEMENT/ADD_ACTIVITY',
  ADD_ACTIVITY_SUCCESS = 'ADMIN_UI/ACTIVITY_MANAGEMENT/ADD_ACTIVITY_SUCCESS',
  ADD_ACTIVITY_FAILED = 'ADMIN_UI/ACTIVITY_MANAGEMENT/ADD_ACTIVITY_FAILED',

  UPDATE_ACTIVITY = 'ADMIN_UI/ACTIVITY_MANAGEMENT/UPDATE_ACTIVITY',
  UPDATE_ACTIVITY_SUCCESS = 'ADMIN_UI/ACTIVITY_MANAGEMENT/UPDATE_ACTIVITY_SUCCESS',
  UPDATE_ACTIVITY_FAILED = 'ADMIN_UI/ACTIVITY_MANAGEMENT/UPDATE_ACTIVITY_FAILED',

  DELETE_ACTIVITY = 'ADMIN_UI/ACTIVITY_MANAGEMENT/DELETE_ACTIVITY',
  DELETE_ACTIVITY_SUCCESS = 'ADMIN_UI/ACTIVITY_MANAGEMENT/DELETE_ACTIVITY_SUCCESS',
  DELETE_ACTIVITY_FAILED = 'ADMIN_UI/ACTIVITY_MANAGEMENT/DELETE_ACTIVITY_FAILED',

  GET_ACTIVITY = 'ADMIN_UI/ACTIVITY_MANAGEMENT/GET_ACTIVITY',
  GET_ACTIVITY_SUCCESS = 'ADMIN_UI/ACTIVITY_MANAGEMENT/GET_ACTIVITY_SUCCESS',
  GET_ACTIVITY_FAILED = 'ADMIN_UI/ACTIVITY_MANAGEMENT/GET_ACTIVITY_FAILED',

  GET_RESTAURANT_LIST = 'ADMIN_UI/ACTIVITY_MANAGEMENT/GET_RESTAURANT_LIST',
  GET_RESTAURANT_LIST_SUCCESS = 'ADMIN_UI/ACTIVITY_MANAGEMENT/GET_RESTAURANT_LIST_SUCCESS',
  GET_RESTAURANT_LIST_FAILED = 'ADMIN_UI/ACTIVITY_MANAGEMENT/GET_RESTAURANT_LIST_FAILED',

  RESET_REDUX = 'ADMIN_UI/ACTIVITY_MANAGEMENT/RESET_REDUX'
}

export default ActionTypes;
