enum ActionTypes {
  GET_DATA = 'ADMIN_UI/APP_MANAGEMENT/GET_DATA',
  GET_DATA_SUCCESS = 'ADMIN_UI/APP_MANAGEMENT/GET_DATA_SUCCESS',
  GET_DATA_FAILED = 'ADMIN_UI/APP_MANAGEMENT/GET_DATA_FAILED',

  SHOW_STATUS_MESSAGE = 'ADMIN_UI/APP_MANAGEMENT/SHOW_STATUS_MESSAGE',
  CLOSE_STATUS_MESSAGE = 'ADMIN_UI/APP_MANAGEMENT/CLOSE_STATUS_MESSAGE',

  LOGOUT = 'ADMIN_UI/APP_MANAGEMENT/LOGOUT',
  LOGOUT_SUCCESS = 'ADMIN_UI/APP_MANAGEMENT/LOGOUT_SUCCESS',
  LOGOUT_FAILED = 'ADMIN_UI/APP_MANAGEMENT/LOGOUT_FAILED',

  RESET_REDUX = 'ADMIN_UI/APP_MANAGEMENT/RESET_REDUX'
}

export default ActionTypes;
