enum ActionTypes {
  GET_ENTRY_LIST = 'ADMIN_UI/ENTRIES_MANAGEMENT/GET_ENTRY_LIST',
  GET_ENTRY_LIST_SUCCESS = 'ADMIN_UI/ENTRIES_MANAGEMENT/GET_ENTRY_LIST_SUCCESS',
  GET_ENTRY_LIST_FAILED = 'ADMIN_UI/ENTRIES_MANAGEMENT/GET_ENTRY_LIST_FAILED',

  POST_ENTRY_FEEDBACK = 'ADMIN_UI/ENTRIES_MANAGEMENT/POST_ENTRY_FEEDBACK',
  POST_ENTRY_FEEDBACK_SUCCESS = 'ADMIN_UI/ENTRIES_MANAGEMENT/POST_ENTRY_FEEDBACK_SUCCESS',
  POST_ENTRY_FEEDBACK_FAILED = 'ADMIN_UI/ENTRIES_MANAGEMENT/POST_ENTRY_FEEDBACK_FAILED',

  RESET_REDUX = 'ADMIN_UI/ENTRIES_MANAGEMENT/RESET_REDUX'
}

export default ActionTypes;
