enum ActionTypes {
  LOGIN = 'ADMIN_UI/AUTH_MANAGEMENT/LOGIN',
  LOGIN_SUCCESS = 'ADMIN_UI/AUTH_MANAGEMENT/LOGIN_SUCCESS',
  LOGIN_FAILED = 'ADMIN_UI/AUTH_MANAGEMENT/LOGIN_FAILED',

  FORGOT_LOGIN_PASSWORD = 'ADMIN_UI/AUTH_MANAGEMENT/FORGOT_LOGIN_PASSWORD',
  FORGOT_LOGIN_PASSWORD_SUCCESS = 'ADMIN_UI/AUTH_MANAGEMENT/FORGOT_LOGIN_PASSWORD_SUCCESS',
  FORGOT_LOGIN_PASSWORD_FAILED = 'ADMIN_UI/AUTH_MANAGEMENT/FORGOT_LOGIN_PASSWORD_FAILED',

  FORGOT_LOGIN_PASSWORD_LINK_VERIFY = 'ADMIN_UI/AUTH_MANAGEMENT/FORGOT_LOGIN_PASSWORD_LINK_VERIFY',
  FORGOT_LOGIN_PASSWORD_LINK_VERIFY_SUCCESS = 'ADMIN_UI/AUTH_MANAGEMENT/FORGOT_LOGIN_PASSWORD_LINK_VERIFY_SUCCESS',
  FORGOT_LOGIN_PASSWORD_LINK_VERIFY_FAILED = 'ADMIN_UI/AUTH_MANAGEMENT/FORGOT_LOGIN_PASSWORD_LINK_VERIFY_FAILED',

  RESET_USER_PASSWORD = 'ADMIN_UI/AUTH_MANAGEMENT/RESET_USER_PASSWORD',
  RESET_USER_PASSWORD_SUCCESS = 'ADMIN_UI/AUTH_MANAGEMENT/RESET_USER_PASSWORD_SUCCESS',
  RESET_USER_PASSWORD_FAILED = 'ADMIN_UI/AUTH_MANAGEMENT/RESET_USER_PASSWORD_FAILED',

  RESET_REDUX = 'ADMIN_UI/AUTH_MANAGEMENT/RESET_REDUX'
}

export default ActionTypes;
